# Generated by Django 3.0.3 on 2020-02-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', help_text='Brief description', max_length=250),
        ),
    ]
